version: '3.3'

services:

    postgresql:
        image: postgres:12.1-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "postgres"
        volumes:
            - ./logs/db:/var/log/postgresql

    java-app:
        build:
            context: ../../
            dockerfile: .deployment/docker/Dockerfile
        ports:
            - 8080:8080
            - 8000:8000
        depends_on:
            - postgresql

networks:
    default:
        ipam:
            driver: default
            config:
                -   subnet: 172.18.0.1/24
#
