version: '3.3'

services:

    postgresql:
        container_name: postgresql
        image: postgres:12.1-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "postgres"
        volumes:
            - ./logs/db:/var/log/postgresql
#
